[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = 'paris' 
optimizer = true
optimizer_runs = 600

[etherscan]
mantle = { key = "$MANTLESCAN_API_KEY", chain=5000 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
