[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = 'paris' 
optimizer = true
optimizer_runs = 600

[rpc_endpoints]
avalanche_fuji = "https://api.avax-test.network/ext/bc/C/rpc"
mantle = "https://rpc.mantle.xyz"

[etherscan]
mantle = { key = "$MANTLESCAN_API_KEY", chain=5000 }

[lint]
exclude_lints = ["screaming-snake-case-const", "screaming-snake-case-immutable", "unsafe-cheatcode", "unchecked-call", "unwrapped-modifier-logic", "asm-keccak256", "mixed-case-variable", "unused-import", "mixed-case-function", "unaliased-plain-import", "unsafe-typecast", "named-struct-fields", "erc20-unchecked-transfer"]
ignore = ["**/test/**/*.t.sol", "**/script/**/*.s.sol"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
